### ISSUE TITLE
Todo before stable release

### ISSUE THREAD

**Issue by PeeHaa** [PeeHaa/AsyncTwitter#15]
- [ ] Check all namespaces of examples
- [ ] Check all namespaces of tests
- [ ] Check all namespaces of source
- [ ] Explain project structure
- [ ] Update readme
- [ ] Check all namespaces of examples
- [ ] Add contribution notes
- [ ] Test the streaming API
- [ ] Branch out the v1 release to the v1 branch and move ampv2 development to master
- [ ] Write documentation
- [ ] Move all GET, POST and DELETE requests into their own namespace
- [ ] Check all parameters
- [ ] Rename all `lang` methods to `langauge`
